config/routes.rb
Rails.application.routes.draw do
  

# original paged app
  # get '/', to: 'tasks#index'
  # root 'tasks#index'

  ACCEPTS_JSON = lambda { |request| request.accepts.include?(:json)}

  scope constraints: ACCEPTS_JSON do
    resources :tasks do
      get :complete
    end
  end


  get '*path', to: 'client_app#show'
  root         to: 'client_app#show'

  
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_app_controller.rb
class ClientAppController < ApplicationController
	def show
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		# @tasks = Task.order(:id)
		render json: Task.order(created_at: :desc)
	end

	def new
		@task = Task.new
	end

	# def create 
	# 	task = Task.new(task_params)
	# 	@tasks = Task.all
	# 	if task.save
	# 		render 'index'
	# 	else
	# 		render 'new'
	# 	end
	# end

	def create
    task = Task.new(task_params)
    if task.save
      render json: task, status: :created
    else
      render_errors(task)
    end
  end

	def edit
		@task = Task.find(params[:id])
	end

	# def update
	# 	task = Task.find(params[:id])
	# 	task.update(task_params)
	# 	redirect_to tasks_path
	# end
	def update
    task = Task.find(params[:id])
    if task.update(task_params)
      render json: task
    else
      render_errors(task)
    end
  end

	# def destroy
	# 	task = Task.find(params[:id])
	# 	task.destroy
	# 	# render 'index'
	# 	redirect_to tasks_path
	# end
	def destroy
    task = Task.find(params[:id])
    if task.destroy
      render json: task
    else
      render_errors(task)
    end
  end
	
	def complete
		task = Task.find(params[:task_id])
		if task.completed == true
			task.update_attributes(completed: false)
		else
			task.update_attributes(completed: true)
		end
		# render 'index'
		redirect_to tasks_path
	end


	private 
		def task_params
			params.require(:task).permit(:description, :completed)
		end

		def render_errors(task)
    render json: {
      error: task.errors.full_messages.join(', ')
    }, status: :bad_request
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_app_helper.rb
module ClientAppHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/client_app/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Too Doos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script type="text/x-template" data-template="task">
    <div class="task">
      <span class="task-description">${description}</span>
      <a href="" class="task-remove-link">X</a>
    </div>
  </script>
  <script type="text/x-template" data-template="new-task-form">
    <form class="new-task-form" action="/tasks" method="post">
      <input type="text" name="task[description]" placeholder="new task" />
      <input type="submit" value="create" />
    </form>
  </script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toodoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<h1>editing task</h1>

<%= form_for @task, method: :patch do |f| %>
<p>
		<%= f.label :description %>
		<%= f.text_field :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
	<div>
	<p>Comment <%= task.id %></p>
	<p><%= task.description %></p>
	<p>Status: <%= task.completed %></p>
	<%= link_to "Edit task #{task.id}", edit_task_path(task) %>
	<% if task.completed %>
	<%= link_to "UnComplete task #{task.id}", task_complete_path(task) %>
	<% else %>
	<%= link_to "Complete task #{task.id}", task_complete_path(task) %>
	<% end %>
	<%= link_to "Destroy", task_path(task), method: :delete  %>

	<p>-------------------------</p>
	</div>
<% end %>

<h2>Add a task</h2>
<%= form_for :task, url: tasks_path do |f| %>
	<p>
		<%= f.label :description %>
		<%= f.text_field :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>